### ISSUE TITLE
Adding icons to data nodes

### ISSUE THREAD

**Issue by ohdangthejam** [NuclearBand/UnityScriptableObjectDatabase#9]
I'd really like to add an icon to each data node in the database (if that node has an icon). My nodes that inherit from DataNode are not in the NuclearBand namespace, so I can't use the line from Odin's RPG example:
`tree.EnumerateTree().AddIcons<BaseUnit>(x => x.icon);`
What would be the best way to implement this feature? I tried adding a Texture to DataNode, but that doesn't work, since AddIcons<DataNode> doesn't seem to add icons to classes inheriting from DataNode. It's also not the most elegant solution since not all DataNodes would benefit from an icon.

**Comment by Tr0sT** [comment]
That's a cool idea. I added Dictionary<Type, Texture> in SODatabaseSettings. Now you can set a different icon for each DataNode subtype.
